language: python

matrix:
  include:
#    - python: 2.6
#      env: TOXENV=py26
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36

before_install:
# install LaTeX stuff
#    - sudo apt-get -qq update
#    - sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
# install required python packages for build and coverage
    - pip install pytest pytest-cov
    - pip install coveralls

install: pip install tox

script:
    - tox

notifications:
email: false

after_success:
    - if [[ $TOXENV == py36 ]]; then
          coveralls;
      fi
